<a href="https://colab.research.google.com/github/TomaszWlo/learning-git-task/blob/master/zadanie_8_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

album = pd.read_html('https://www.officialcharts.com/chart-news/the-best-selling-albums-of-all-time-on-the-official-uk-chart__15551/', header=0)
df = album[0]

df.rename(columns={'TITLE':'TYTUŁ', "ARTIST":'ARTYSTA', 'YEAR':'ROK', 'HIGH POSN':'MAX POZ'}, inplace=True)
print(df.columns)

df.columns = df.columns.str.capitalize()
print(df.columns)

df.drop('Max poz', axis=1, inplace=True)
print(df.columns)

Index(['POS', 'TYTUŁ', 'ARTYSTA', 'ROK', 'MAX POZ'], dtype='object')
Index(['Pos', 'Tytuł', 'Artysta', 'Rok', 'Max poz'], dtype='object')
Index(['Pos', 'Tytuł', 'Artysta', 'Rok'], dtype='object')

In [16]:
df['Artysta'].unique()

array(['QUEEN', 'ABBA', 'BEATLES', 'ADELE', 'OASIS', 'MICHAEL JACKSON',
       'PINK FLOYD', 'DIRE STRAITS', 'FLEETWOOD MAC', 'MADONNA',
       'AMY WINEHOUSE', 'SIMPLY RED', 'SHANIA TWAIN',
       'BOB MARLEY & THE WAILERS', 'JAMES BLUNT', 'VERVE', 'MEAT LOAF',
       'SIMON & GARFUNKEL', 'ORIGINAL SOUNDTRACK', 'LEONA LEWIS',
       'MICHAEL BUBLE', 'DIDO', 'DAVID GRAY', 'CORRS', 'SPICE GIRLS',
       'LADY GAGA', 'COLDPLAY', 'KINGS OF LEON', 'TAKE THAT', 'KEANE',
       'U2', 'JEFF WAYNE', 'SCISSOR SISTERS', 'PHIL COLLINS',
       'ALANIS MORISSETTE', 'MIKE OLDFIELD', 'TRAVIS', 'TRACY CHAPMAN',
       'ROBBIE WILLIAMS', 'ED SHEERAN', 'NORAH JONES', 'PAUL SIMON',
       'ORIGINAL CAST RECORDING', 'GEORGE MICHAEL', 'EMINEM',
       'SNOW PATROL', 'REM'], dtype=object)

In [17]:
df['Artysta'].nunique()

47

In [20]:
df['Artysta'].value_counts().head(7)

Artysta
TAKE THAT          3
COLDPLAY           3
QUEEN              2
ADELE              2
MICHAEL JACKSON    2
ABBA               2
BEATLES            2
Name: count, dtype: int64

In [33]:
df['Rok'].value_counts().head(7).sort_values(ascending=False)

Rok
1987    4
2000    4
2006    3
1977    3
1998    3
1997    3
2004    3
Name: count, dtype: int64

In [23]:
print(df['Rok'].max())

2015

In [24]:
len(df[(df['Rok']>1960) & (df['Rok'] < 1990)])

21

In [34]:
df.loc[df.groupby('Artysta')['Rok'].idxmin(), ['Artysta', 'Tytuł', 'Rok']].sort_values('Rok').head(10)

                    Artysta                                 Tytuł   Rok
51  ORIGINAL CAST RECORDING                    THE SOUND OF MUSIC  1965
2                   BEATLES  SGT PEPPER'S LONELY HEARTS CLUB BAND  1967
20        SIMON & GARFUNKEL            BRIDGE OVER TROUBLED WATER  1970
41            MIKE OLDFIELD                         TUBULAR BELLS  1973
6                PINK FLOYD             THE DARK SIDE OF THE MOON  1973
45                     ABBA                         GREATEST HITS  1975
46      ORIGINAL SOUNDTRACK                                GREASE  1977
18                MEAT LOAF                       BAT OUT OF HELL  1977
10            FLEETWOOD MAC                               RUMOURS  1977
36               JEFF WAYNE                 THE WAR OF THE WORLDS  1978

In [35]:
df.to_csv('Sorted table')